# Generated by Django 3.0.1 on 2020-02-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_rasp_parada', models.DateTimeField()),
                ('time_created_parada', models.DateTimeField(auto_now_add=True)),
                ('siniestro_parada', models.BooleanField(default=False)),
                ('prep_asiento', models.BooleanField(default=False)),
                ('nombre_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_parada', to='carga.Parada')),
            ],
            options={
                'verbose_name': 'Datos_Parada',
                'verbose_name_plural': 'Datos_Paradas',
                'ordering': ['nombre_parada'],
            },
        ),
    ]
