# Generated by Django 3.0.7 on 2020-06-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_bus', '0001_initial'),
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicAsientoConsulta',
            fields=[
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carga.Parada')),
                ('time_solic', models.DateTimeField()),
                ('viajes_inicios', models.ManyToManyField(to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'SolicAsientoConsulta',
                'verbose_name_plural': 'SolicAsientoConsultas',
                'ordering': ['parada'],
            },
        ),
        migrations.CreateModel(
            name='SolicAsiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_solic', models.DateTimeField()),
                ('estado_solicitud', models.CharField(choices=[('I', 'INACTIVO'), ('A', 'ACTIVO')], default='I', max_length=10)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Parada')),
                ('viajes_inicios', models.ManyToManyField(to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'SolicAsiento',
                'verbose_name_plural': 'Solicitudes de Asiento',
                'ordering': ['time_solic'],
            },
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_solic', models.DateTimeField()),
                ('estado_solicitud', models.CharField(choices=[('I', 'INACTIVO'), ('A', 'ACTIVO')], default='I', max_length=10)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Parada')),
            ],
            options={
                'verbose_name': 'SiniestroParada',
                'verbose_name_plural': 'Siniestros',
                'ordering': ['time_solic'],
            },
        ),
        migrations.CreateModel(
            name='Datos_Parada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_rasp_parada', models.DateTimeField()),
                ('time_created_parada', models.DateTimeField(auto_now_add=True)),
                ('siniestro_parada', models.BooleanField(default=False)),
                ('prep_asiento', models.BooleanField(default=False)),
                ('nombre_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_parada', to='carga.Parada')),
            ],
            options={
                'verbose_name': 'Datos_Parada',
                'verbose_name_plural': 'Datos_Paradas',
                'ordering': ['nombre_parada'],
            },
        ),
    ]
