# Generated by Django 3.0.1 on 2020-03-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200318_0103'),
        ('carga', '0001_initial'),
        ('api_parada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicAsientoConsulta',
            fields=[
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carga.Parada')),
                ('time_solic', models.DateTimeField()),
                ('viajes_inicios', models.ManyToManyField(to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'SolicAsientoConsulta',
                'verbose_name_plural': 'SolicAsientoConsultas',
                'ordering': ['parada'],
            },
        ),
        migrations.CreateModel(
            name='SolicAsiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_solic', models.DateTimeField()),
                ('estado_solicitud', models.CharField(choices=[('I', 'INACTIVO'), ('A', 'ACTIVO')], default='I', max_length=10)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Parada')),
                ('viajes_inicios', models.ManyToManyField(to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'SolicAsiento',
                'verbose_name_plural': 'Solicitudes de Asiento',
                'ordering': ['time_solic'],
            },
        ),
    ]
