# Generated by Django 3.0.1 on 2020-03-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200318_0103'),
        ('api_parada', '0003_auto_20200319_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicasiento',
            name='viajes_inicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_inicios_solicasiento', to='api_bus.Viaje_Incio'),
        ),
    ]
