# Generated by Django 3.0.1 on 2020-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200318_0103'),
        ('api_parada', '0004_auto_20200319_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicasiento',
            name='viajes_inicios',
        ),
        migrations.AddField(
            model_name='solicasiento',
            name='viajes_inicios',
            field=models.ManyToManyField(to='api_bus.Bus_Datos_Update'),
        ),
        migrations.AlterField(
            model_name='solicasientoconsulta',
            name='viajes_inicios',
            field=models.ManyToManyField(to='api_bus.Bus_Datos_Update'),
        ),
    ]
