# Generated by Django 3.0.1 on 2020-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parada', '0009_auto_20200320_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_parada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
