# Generated by Django 3.0.1 on 2020-04-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200318_0103'),
        ('api_parada', '0010_auto_20200415_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicasientoconsulta',
            name='viajes_inicios',
        ),
        migrations.AddField(
            model_name='solicasientoconsulta',
            name='viajes_inicios',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='api_bus.Viaje_Incio'),
            preserve_default=False,
        ),
    ]
