# Generated by Django 3.0.1 on 2020-04-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200318_0103'),
        ('api_parada', '0011_auto_20200428_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicasientoconsulta',
            name='viajes_inicios',
        ),
        migrations.AddField(
            model_name='solicasientoconsulta',
            name='viajes_inicios',
            field=models.ManyToManyField(to='api_bus.Viaje_Incio'),
        ),
    ]
