# Generated by Django 3.0.1 on 2019-12-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Linea_Ramal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linea', models.CharField(max_length=200)),
                ('ramal', models.CharField(max_length=200)),
                ('recorrido', models.TextField()),
            ],
            options={
                'verbose_name': 'Linea_Ramal',
                'verbose_name_plural': 'Lineas_Ramales',
                'ordering': ['linea'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['nro'],
            },
        ),
    ]
