# Generated by Django 3.0.1 on 2020-02-04 15:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('chapa', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['chapa', 'empresa_id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=13)),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('location_parada', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RaspberryParada',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parada_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.Parada')),
            ],
            options={
                'verbose_name': 'RaspberryParada',
                'verbose_name_plural': 'RaspberrysParadas',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='RaspberryBus',
            fields=[
                ('serial_rasp_bus', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.Bus')),
            ],
            options={
                'verbose_name': 'RaspberryBus',
                'verbose_name_plural': 'RaspberrysBuses',
                'ordering': ['serial_rasp_bus'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('nro', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
                'ordering': ['nro'],
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('mpoly', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('linea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Linea')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci_nro', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(choices=[('PY', 'Paraguaya'), ('AR', 'Argentina'), ('BR', 'Brasilera'), ('BO', 'Boliviana'), ('PE', 'Peruana'), ('CH', 'Chilena')], default='PY', max_length=10)),
                ('observacion', models.TextField()),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['ci_nro'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa'),
        ),
    ]
