# Generated by Django 3.0.1 on 2020-02-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='tipo_parada',
            field=models.CharField(choices=[('T1', 'Tramo1'), ('T2', 'Tramo2')], default='T1', max_length=10),
        ),
    ]
