# Generated by Django 3.0.1 on 2020-01-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('empresa_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Lineas',
                'ordering': ['nro'],
            },
        ),
    ]
