# Generated by Django 3.0.1 on 2020-01-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
