# Generated by Django 3.0.1 on 2020-01-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_empresa_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['nro'], 'verbose_name': 'Linea', 'verbose_name_plural': 'Lineas'},
        ),
        migrations.AlterField(
            model_name='linea',
            name='nro',
            field=models.CharField(max_length=200),
        ),
    ]
