# Generated by Django 3.0.1 on 2020-01-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_auto_20200111_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('linea_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Linea_Ramal',
        ),
    ]
