# Generated by Django 3.0.1 on 2020-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_auto_20200111_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='linea',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
