# Generated by Django 3.0.1 on 2020-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0010_auto_20200111_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='ci_nro',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
