# Generated by Django 3.0.1 on 2020-01-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0011_chofer_ci_nro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='nacionalidad',
            field=models.CharField(choices=[('PY', 'Paraguaya'), ('AR', 'Argentina'), ('BR', 'Brasilera'), ('BO', 'Boliviana'), ('PE', 'Peruana'), ('CH', 'Chilena')], default='PY', max_length=10),
        ),
    ]
