# Generated by Django 3.0.1 on 2020-01-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0012_auto_20200111_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='empresa_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chofer',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parada',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parada',
            name='nro',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('chapa', models.CharField(max_length=8)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Empresa')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['chapa', 'chapa'],
            },
        ),
    ]
