# Generated by Django 3.0.1 on 2020-01-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0013_auto_20200111_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['chapa', 'empresa_id'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='chofer',
            options={'ordering': ['ci_nro'], 'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
    ]
