# Generated by Django 3.0.1 on 2020-01-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0014_auto_20200111_2221'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['chapa', 'empresa_id'], name='carga_bus_chapa_75e9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['ci_nro', 'nombre', 'apellido', 'empresa_id'], name='carga_chofe_ci_nro_a3236e_idx'),
        ),
    ]
