# Generated by Django 3.0.1 on 2020-01-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0015_auto_20200111_2222'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bus',
            name='carga_bus_chapa_75e9c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='chofer',
            name='carga_chofe_ci_nro_a3236e_idx',
        ),
    ]
