# Generated by Django 3.0.1 on 2020-01-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0016_auto_20200111_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50)),
                ('bus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.Bus')),
            ],
        ),
    ]
