# Generated by Django 3.0.1 on 2020-01-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0017_raspberry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raspberry',
            new_name='RaspberryBus',
        ),
        migrations.AlterModelOptions(
            name='raspberrybus',
            options={'ordering': ['serial'], 'verbose_name': 'RaspberryBus', 'verbose_name_plural': 'RaspberrysBuses'},
        ),
        migrations.CreateModel(
            name='RaspberryParada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50)),
                ('parada_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carga.Parada')),
            ],
            options={
                'verbose_name': 'RaspberryParada',
                'verbose_name_plural': 'RaspberrysParadas',
                'ordering': ['serial'],
            },
        ),
    ]
