# Generated by Django 3.0.1 on 2020-03-12 02:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje_Incio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_rasp_logueo', models.DateTimeField()),
                ('time_created_logueo', models.DateTimeField(auto_now_add=True)),
                ('chofer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Chofer')),
                ('itinerario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Itinerario')),
                ('raspberry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.RaspberryBus')),
            ],
            options={
                'verbose_name': 'Viaje_Incio',
                'verbose_name_plural': 'Viajes_Inicios',
                'ordering': ['time_rasp_logueo'],
            },
        ),
        migrations.CreateModel(
            name='Bus_Datos_Update',
            fields=[
                ('viaje_inicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='viaje_inicio', serialize=False, to='api_bus.Viaje_Incio')),
                ('time_rasp', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location_bus', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('siniestro_bus', models.BooleanField(default=False)),
                ('sensor_asiento', models.BooleanField(default=False)),
                ('estado_viaje', models.CharField(choices=[('T1', 'Tramo1'), ('T2', 'Tramo2'), ('I', 'Intermedio'), ('P', 'Preparado')], default='PY', max_length=10)),
            ],
            options={
                'verbose_name': 'Bus_Datos_Update',
                'verbose_name_plural': 'Bus_Datos_Updates',
                'ordering': ['viaje_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicAsientoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_solic', models.DateTimeField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_parada_solic_asiento_historico', to='carga.Parada')),
                ('viaje_inicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_inicio_solic_asiento_historico', to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'SolicAsiento',
                'verbose_name_plural': 'Solicitudes de Asiento Historico',
                'ordering': ['time_solic'],
            },
        ),
        migrations.CreateModel(
            name='SolicAsiento',
            fields=[
                ('time_solic', models.DateTimeField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nombre_parada_solic_asiento', serialize=False, to='carga.Parada')),
                ('viaje_inicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_inicio_solic_asiento', to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'SolicAsiento',
                'verbose_name_plural': 'Solicitudes de Asiento',
                'ordering': ['time_solic'],
            },
        ),
        migrations.CreateModel(
            name='Bus_Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_rasp', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location_bus', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('siniestro_bus', models.BooleanField(default=False)),
                ('sensor_asiento', models.BooleanField(default=False)),
                ('estado_viaje', models.CharField(choices=[('T1', 'Tramo1'), ('T2', 'Tramo2'), ('I', 'Intermedio'), ('P', 'Preparado')], default='PY', max_length=10)),
                ('viaje_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bus.Viaje_Incio')),
            ],
            options={
                'verbose_name': 'Bus_Dato',
                'verbose_name_plural': 'Bus_Datos',
                'ordering': ['id'],
            },
        ),
    ]
