# Generated by Django 3.0.1 on 2019-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(max_length=200)),
                ('viaje', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'bus_geo',
                'verbose_name_plural': 'bus_geo_ubicaciones',
                'ordering': ['viaje'],
            },
        ),
    ]
