# Generated by Django 3.0.1 on 2020-02-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
        ('api_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_incio',
            name='itinerario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='carga.Itinerario'),
        ),
    ]
