# Generated by Django 3.0.1 on 2020-02-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_parada_tipo_parada'),
        ('api_bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicAsiento',
            fields=[
                ('viaje_inicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='viaje_inicio_solic_asiento', serialize=False, to='api_bus.Viaje_Incio')),
                ('time_solic', models.DateTimeField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_parada_solic_asiento', to='carga.Parada')),
            ],
        ),
    ]
