# Generated by Django 3.0.7 on 2020-06-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus_geo',
            options={'ordering': ['viaje'], 'verbose_name': 'Bus_geo', 'verbose_name_plural': 'bus_geo_ubicaciones'},
        ),
    ]
