# Generated by Django 3.0.1 on 2020-03-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
        ('api_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicasiento',
            name='parada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nombre_parada_solic_asiento', serialize=False, to='carga.Parada'),
        ),
        migrations.AlterField(
            model_name='solicasiento',
            name='viaje_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_inicio_solic_asiento', to='api_bus.Viaje_Incio'),
        ),
    ]
