# Generated by Django 3.0.1 on 2020-02-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Datos_Prueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_datos_update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_datos_update', to='api_bus.Bus_Datos_Update')),
            ],
        ),
    ]
