# Generated by Django 3.0.1 on 2020-03-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0002_auto_20200311_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicasientohistorico',
            name='parada',
        ),
        migrations.RemoveField(
            model_name='solicasientohistorico',
            name='viaje_inicio',
        ),
        migrations.AlterField(
            model_name='bus_datos_update',
            name='viaje_inicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='viaje_inicio_bus_datos_update', serialize=False, to='api_bus.Viaje_Incio'),
        ),
        migrations.DeleteModel(
            name='SolicAsiento',
        ),
        migrations.DeleteModel(
            name='SolicAsientoHistorico',
        ),
    ]
