# Generated by Django 3.0.1 on 2020-02-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0002_solicasiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicasiento',
            options={'ordering': ['time_solic'], 'verbose_name': 'SolicAsiento', 'verbose_name_plural': 'Solicitudes de Asiento'},
        ),
    ]
