# Generated by Django 3.0.1 on 2020-02-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
        ('api_bus', '0002_bus_datos_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_incio',
            name='chofer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Chofer'),
        ),
        migrations.AlterField(
            model_name='viaje_incio',
            name='raspberry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.RaspberryBus'),
        ),
    ]
