# Generated by Django 3.0.1 on 2020-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0002_auto_20200106_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viaje', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('time_rasp', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('siniestro_bus', models.BooleanField(default=False)),
                ('sensor_asiento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bus_Dato',
                'verbose_name_plural': 'Bus_Datos',
                'ordering': ['id_viaje'],
            },
        ),
        migrations.DeleteModel(
            name='Bus_geo',
        ),
    ]
