# Generated by Django 3.0.1 on 2020-02-10 17:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200207_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Datos_Update_prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_rasp', models.DateTimeField()),
                ('location_bus', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('viaje_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bus.Viaje_Incio')),
            ],
        ),
    ]
