# Generated by Django 3.0.1 on 2020-02-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0003_auto_20200205_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_datos',
            name='viaje_inicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_inicio', to='api_bus.Viaje_Incio'),
        ),
    ]
