# Generated by Django 3.0.1 on 2020-02-06 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
        ('api_bus', '0005_auto_20200205_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_datos',
            name='viaje_inicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_inicio', to='api_bus.Viaje_Incio'),
        ),
        migrations.AlterField(
            model_name='viaje_incio',
            name='itinerario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Itinerario'),
        ),
    ]
