# Generated by Django 3.0.1 on 2020-02-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bus', '0007_auto_20200206_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus_datos',
            old_name='viaje_inicio_id',
            new_name='viaje_inicio',
        ),
    ]
