# Generated by Django 3.0.1 on 2020-02-26 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_parada_tipo_parada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_auto_20200226_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci_nro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.Chofer'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
